#' @name ejscreenformulas
#' @docType data
#' @title EJSCREEN 2015 Formulas and Fieldnames
#' @description This provides fieldnames and formulas required by the \pkg{ejscreen} package.
#'  Formulas can be viewed this way: sort(ejscreenformulas$formula)
#' @usage data('ejscreenformulas')
#' @source See related Technical Documentation at \url{http://www.epa.gov/ejscreen}
#' @keywords EJ, environmental justice, datasets, demographic
#' @format A data.frame: \cr\cr
#' > str(ejscreenformulas) \cr
#' 'data.frame':	470 obs. of  8 variables: \cr
#' \itemize{
#'  \item $ gdbfieldname     : chr  NA NA NA NA ...
#'  \item $ Rfieldname       : chr  "ageunder5m" "age5to9m" "age10to14m" "age15to17m" ...
#'  \item $ acsfieldname     : chr  "B01001.003" "B01001.004" "B01001.005" "B01001.006" ...
#'  \item $ type             : chr  "ACS" "ACS" "ACS" "ACS" ...
#'  \item $ glossaryfieldname: chr  NA NA NA NA ...
#'  \item $ formula          : chr  NA NA NA NA ...
#'  \item $ acsfieldnamelong : chr  "Under 5 years|SEX BY AGE" "5 to 9 years|SEX BY AGE" "10 to 14 years|SEX BY AGE" "15 to 17 years|SEX BY AGE" ...
#'  \item $ universe         : chr  "Universe:  Total population" "Universe:  Total population" "Universe:  Total population" "Universe:  Total population" ...
#' }
NULL
